org.gradle.jvmargs=-Xmx4G

android.useAndroidX=true
android.enableJetifier=true

org.gradle.java.home=C:\\Program Files\\Java\\jdk-17

flutter.deferred-components=false

# REQUIRED FOR PLAY STORE 16 KB PAGES
android.experimental.enable16kPages=true

# Recommended
android.enableR8.fullMode=true
android.experimental.enableArtProfiles=true
android.enableDexingArtifactTransform=true
